# Data Cleaning & Preprocessing

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('movies_data.csv')
df.head()

,Unnamed: 0,title,year,certification,genres,runtime,director,awards,original_language,budget,revenue,rating
0,0,Avatar Aang: The Last Airbender,2026,PG,"Animation , Action , Adventure , and Fantasy",1h 39m,Tim Hedrick,NaN,English,-,-,92
1,1,Accidental Partners,2026,PG-13,Comedy and Romance,1h 50m,Ihtzi Hurtado,NaN,Spanish; Castilian,-,-,89
2,2,Swapped,2026,PG,"Adventure , Animation , Family , and Fantasy",1h 42m,Nathan Greno,NaN,English,7,7,89
3,3,Facing El Chapo,2026,R,"Crime , Action , and Thriller",1h 31m,Chava Cartas,NaN,Spanish; Castilian,-,-,88
4,4,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025,R,"Animation , Action , and Fantasy",2h 36m,Haruo Sotozaki,3 Wins,Japanese,20000000,733030221,88

In [4]:
df.columns

Index(['Unnamed: 0', 'title', 'year', 'certification', 'genres', 'runtime',
       'director', 'awards', 'original_language', 'budget', 'revenue',
       'rating'],
      dtype='object')

In [5]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
df.shape

(2000, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2000 non-null   object
 1   year               2000 non-null   int64
 2   certification      1980 non-null   object
 3   genres             2000 non-null   object
 4   runtime            2000 non-null   object
 5   director           1998 non-null   object
 6   awards             558 non-null    object
 7   original_language  2000 non-null   object
 8   budget             2000 non-null   object
 9   revenue            2000 non-null   object
 10  rating             2000 non-null   int64
dtypes: int64(2), object(9)
memory usage: 172.0+ KB

In [8]:
# Missing values
df.isnull().sum()

title                   0
year                    0
certification          20
genres                  0
runtime                 0
director                2
awards               1442
original_language       0
budget                  0
revenue                 0
rating                  0
dtype: int64

In [9]:
df['certification'] = df['certification'].fillna('Unknown')
df['director'] = df['director'].fillna('Unknown')

In [10]:
df['certification'].unique()

array(['PG', 'PG-13', 'R', 'NR', 'U', '15', 'L', 'C', '12', 'G',
       'Unknown', 'ALL', 'A', 'PG13', 'T', '0+', '13+', '18', '6', '14A',
       'NC-17', '19', '16', '13', 'M/12', 'AL', 'B-15', 'Btl', 'TP', '14',
       '7', 'M', '0', '14+', 'M18', '9', 'B', '15+', 'APTA', 'UA', '16+',
       '18+', 'S', 'R 18+', '18A', 'R15+', '12+', 'IIB', 'U/A 13+',
       'Genel İzleyici Kitlesi', '13A', '10', '6+', '12A', 'Ai', 'PG12',
       'MA 15+', '8'], dtype=object)

In [11]:
# Transforming the Certification Column
rating_map = {
    # Family Friendly
    'G': 'Family Friendly',
    'U': 'Family Friendly',
    '0': 'Family Friendly',
    '0+': 'Family Friendly',
    'ALL': 'Family Friendly',
    'L': 'Family Friendly',
    'B': 'Family Friendly',
    'C': 'Family Friendly',
    'AL': 'Family Friendly',
    'Genel İzleyici Kitlesi': 'Family Friendly',
    'PG': 'Family Friendly',
    '6': 'Family Friendly',
    '6+': 'Family Friendly',
    '7': 'Family Friendly',
    '8': 'Family Friendly',
    '9': 'Family Friendly',
    '10': 'Family Friendly',
    '12': 'Family Friendly',
    '12+': 'Family Friendly',
    '12A': 'Family Friendly',
    'PG12': 'Family Friendly',
    'M/12': 'Family Friendly',

    # Teen
    'PG-13': 'Teen',
    'PG13': 'Teen',
    '13': 'Teen',
    '13+': 'Teen',
    '13A': 'Teen',
    'U/A 13+': 'Teen',
    '14': 'Teen',
    '14+': 'Teen',
    '14A': 'Teen',
    '15': 'Teen',
    '15+': 'Teen',
    'R15+': 'Teen',
    'B-15': 'Teen',
    'T': 'Teen',
    'MA 15+': 'Teen',

    # Adult
    'R': 'Adult',
    '18': 'Adult',
    '18+': 'Adult',
    '18A': 'Adult',
    'R 18+': 'Adult',
    'NC-17': 'Adult',
    '16': 'Adult',
    '16+': 'Adult',
    '19': 'Adult',
    'M18': 'Adult',
    'S': 'Adult',
    'IIB': 'Adult',

    # Unknown
    'NR': 'Unknown',
    'Unknown': 'Unknown',
    'A': 'Unknown',
    'Btl': 'Unknown',
    'TP': 'Unknown',
    'M': 'Unknown',
    'APTA': 'Unknown',
    'UA': 'Unknown',
    'Ai': 'Unknown'
}

df['age_rating'] = df['certification'].map(rating_map)

In [12]:
df['age_rating'].unique()

array(['Family Friendly', 'Teen', 'Adult', 'Unknown'], dtype=object)

In [13]:
df.drop(columns=['certification'], inplace=True)

In [14]:
# Transforming the Awards column
df['awarded'] = df['awards'].notna().astype(int)
df.drop(columns=['awards'], inplace=True)

In [15]:
df['awarded'].value_counts()

awarded
0    1442
1     558
Name: count, dtype: int64

In [16]:
df.columns

Index(['title', 'year', 'genres', 'runtime', 'director', 'original_language',
       'budget', 'revenue', 'rating', 'age_rating', 'awarded'],
      dtype='object')

In [17]:
df['genres'] = df['genres'].str.replace(' and ',', ').str.replace(',,',',')

In [18]:
# New column Primary Genre of the Movie
df['primary_genre'] = df['genres'].str.split(', ').str[0].str.strip()
df['primary_genre'].unique()

array(['Animation', 'Comedy', 'Adventure', 'Crime', 'Drama', 'Music',
       'Science Fiction', 'Action', 'Fantasy', 'Thriller', 'Western',
       'Documentary', 'Family', 'Horror', 'Romance', 'War', 'Mystery',
       'History', 'TV Movie'], dtype=object)

In [19]:
# Transforming the runtime to runtime in minutes
def convert_runtime(runtime):
    hours = 0
    minutes = 0

    if 'h' in runtime:
        hours = int(runtime.split('h')[0].strip())

    if 'm' in runtime:
        minutes_part = runtime.split('h')[-1]
        minutes = int(minutes_part.replace('m', '').strip())

    return hours * 60 + minutes

df['runtime_minutes'] = df['runtime'].apply(convert_runtime)
df.drop(columns=['runtime'], inplace=True)

In [20]:
# Standardizing the budget and revenue column
import numpy as np

df[['budget', 'revenue']] = df[['budget', 'revenue']].replace('-', np.nan)

In [21]:
df[['budget', 'revenue']] = df[['budget', 'revenue']].apply(
    pd.to_numeric, errors='coerce'
)

In [22]:
df.loc[df['budget'] < 100, 'budget'] = np.nan

In [23]:
# Duplicate rows
df.duplicated().sum()

np.int64(0)

In [24]:
# Same titles
df.duplicated(subset='title').sum()

np.int64(16)

In [25]:
# Same titles but different director and year
df[df.duplicated(subset='title', keep=False)]

,title,year,genres,director,original_language,budget,revenue,rating,age_rating,awarded,primary_genre,runtime_minutes
10,12 Angry Men,1957,Drama,Reginald Rose,English,397751.0,4360000.0,86,Unknown,0,Drama,97
56,Whiplash,2014,"Drama , Music , Thriller",Damien Chazelle,English,3300000.0,50307484.0,84,Adult,1,Drama,107
105,Miracle in Cell No. 7,2019,Drama,Mehmet Ada Öztekin,Turkish,NaN,28000000.0,83,Teen,0,Drama,132
119,Gladiator,2000,"Action , Drama , Adventure",David Franzoni,English,103000000.0,465516248.0,82,Adult,1,Action,155
183,Scarface,1983,"Action , Crime , Drama",Brian De Palma,English,25000000.0,66023329.0,82,Adult,0,Action,170
427,How to Train Your Dragon,2025,"Fantasy , Family , Action , Adventure",Dean DeBlois,English,150000000.0,636351148.0,79,Family Friendly,1,Fantasy,125
468,The Count of Monte Cristo,2024,"Adventure , Action , Drama",Alexandre de La Patellière,French,46000000.0,75360860.0,79,Unknown,1,Adventure,178
494,Miracle in Cell No. 7,2013,"Drama, Comedy",Lee Hwan-kyung,Korean,NaN,80300000.0,79,Teen,0,Drama,128
548,How to Train Your Dragon,2010,"Fantasy , Adventure , Animation , Family",Chris Sanders,English,165000000.0,495141736.0,79,Family Friendly,0,Fantasy,98
610,Dogman,2023,"Action , Drama , Crime",Luc Besson,French,NaN,4082217.0,78,Adult,0,Action,115
729,Shelter,2026,"Action , Crime , Thriller",Ric Roman Waugh,English,50000000.0,53933639.0,78,Adult,0,Action,107
736,Whiplash,2013,"Drama, Music",Damien Chazelle,English,NaN,NaN,78,Unknown,0,Drama,18
774,All Quiet on the Western Front,1930,"Drama, War",Lewis Milestone,English,1448864.0,3270000.0,78,Unknown,0,Drama,133
783,Shelter,2007,"Drama, Romance",Jonah Markowitz,English,500000.0,142666.0,78,Adult,0,Drama,89
806,All Quiet on the Western Front,2022,"War, Drama",Edward Berger,German,20000000.0,NaN,77,Adult,1,War,147
840,Beauty and the Beast,1991,"Romance , Family , Animation , Fantasy",Kirk Wise,English,25000000.0,424967620.0,77,Family Friendly,1,Romance,84
910,12 Angry Men,1997,"Drama, TV Movie",William Friedkin,English,1750000.0,2000000.0,77,Teen,0,Drama,117
927,The Count of Monte Cristo,2002,"Adventure , Drama , History , Action",Kevin Reynolds,English,35000000.0,75395048.0,77,Teen,0,Adventure,131
1072,The Killer,2022,"Action , Crime , Thriller",Choi Jae-hoon,Korean,NaN,595112.0,76,Adult,0,Action,95
1075,Gladiator,1992,Drama,Robert Mark Kamen,English,20000000.0,9223441.0,76,Adult,0,Drama,101
1104,Frankenstein,2025,"Drama , Fantasy , Horror",Guillermo del Toro,English,120000000.0,480678.0,76,Adult,1,Drama,150
1174,The Killer,1989,"Action , Crime , Drama , Thriller",John Woo,Cantonese,NaN,2350174.0,76,Adult,0,Action,110
1279,Rise,2022,Drama,Akin Omotoso,English,NaN,NaN,76,Family Friendly,0,Drama,113
1338,The Girl with the Dragon Tattoo,2009,"Drama , Thriller , Crime , Mystery",Niels Arden Oplev,Swedish,13000000.0,109421911.0,75,Adult,1,Drama,152
1432,Dogman,2018,"Crime , Drama , Thriller",Matteo Garrone,Italian,NaN,5080147.0,75,Teen,0,Crime,103
1467,Beauty and the Beast,1946,"Drama , Fantasy , Romance",Jean Cocteau,French,NaN,NaN,75,Unknown,0,Drama,96
1610,Frankenstein,1931,"Drama , Horror , Science Fiction",James Whale,English,291000.0,12000000.0,75,Family Friendly,0,Drama,70
1692,Happiness,1965,"Drama, Romance",Agnès Varda,French,NaN,NaN,74,Adult,0,Drama,80
1740,Happiness,1998,"Comedy, Drama",Todd Solondz,English,3000000.0,2800000.0,74,Adult,0,Comedy,140
1841,Scarface,1932,"Crime , Action , Drama , Thriller",Howard Hawks,English,800000.0,600000.0,74,Adult,0,Crime,93
1921,Rise,2022,"Comedy , Drama , Family",Cédric Klapisch,French,7780000.0,11196824.0,74,Family Friendly,0,Comedy,117
1924,The Girl with the Dragon Tattoo,2011,"Thriller , Crime , Mystery",David Fincher,English,90000000.0,232617430.0,74,Adult,1,Thriller,158

In [26]:
# New Features - Profit, ROI, Genre Count
df['profit'] = df['revenue'] - df['budget']
df['roi'] = (df['revenue'] - df['budget'])*100 / df['budget']
df['genre_count'] = df['genres'].str.count(',') + 1

In [27]:
df.describe()

,year,budget,revenue,rating,awarded,runtime_minutes,profit,roi,genre_count
count,2000.000000,1.276000e+03,1.450000e+03,2000.000000,2000.00000,2000.000000,1.178000e+03,1178.000000,2000.000000
mean,1998.188500,3.263603e+07,1.366577e+08,77.231000,0.27900,113.613000,1.301944e+08,841.568943,2.528500
std,24.707695,5.317177e+07,2.876187e+08,2.806168,0.44862,31.720235,2.722590e+08,3085.166872,1.045818
min,1902.000000,1.170000e+02,6.000000e+00,74.000000,0.00000,4.000000,-1.856000e+08,-99.999839,1.000000
25%,1985.000000,3.000000e+06,5.666000e+06,75.000000,0.00000,97.000000,3.721178e+06,71.642673,2.000000
50%,2007.000000,1.200000e+07,3.039428e+07,77.000000,0.00000,112.000000,2.945664e+07,285.692388,3.000000
75%,2018.000000,3.400000e+07,1.196475e+08,79.000000,1.00000,129.000000,1.186961e+08,668.678539,3.000000
max,2026.000000,4.600000e+08,2.923706e+09,92.000000,1.00000,367.000000,2.686706e+09,67332.895333,7.000000

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2000 non-null   object
 1   year               2000 non-null   int64
 2   genres             2000 non-null   object
 3   director           2000 non-null   object
 4   original_language  2000 non-null   object
 5   budget             1276 non-null   float64
 6   revenue            1450 non-null   float64
 7   rating             2000 non-null   int64
 8   age_rating         2000 non-null   object
 9   awarded            2000 non-null   int64
 10  primary_genre      2000 non-null   object
 11  runtime_minutes    2000 non-null   int64
 12  profit             1178 non-null   float64
 13  roi                1178 non-null   float64
 14  genre_count        2000 non-null   int64
dtypes: float64(4), int64(5), object(6)
memory usage: 234.5+ KB

In [29]:
# Cleaned and Transformed Data
df.to_csv('movies_data_cleaned.csv', index=False)